In [1]:
import pandas as pd

In [2]:
data ={
"student" :["A", "B", "C", "D", "E"],
"Math": [78, 90, 67, 95, 88],
"Science": [85, 88, 76, 92, 79],
"English": [82, 85, 80, 90, 84]
}
df = pd.DataFrame(data)

In [3]:
print(df)

  student  Math  Science  English
0       A    78       85       82
1       B    90       88       85
2       C    67       76       80
3       D    95       92       90
4       E    88       79       84

In [6]:
df.columns

Index(['student', 'Math', 'Science', 'English'], dtype='object')

In [7]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [8]:
df.shape

(5, 4)

In [9]:
df.head(3)

  student  Math  Science  English
0       A    78       85       82
1       B    90       88       85
2       C    67       76       80

In [11]:
df.to_csv("students.csv",index= False)

In [12]:
import os

In [14]:
print(os.getcwd())

c:\Users\premier\AppData\Local\Programs\Microsoft VS Code

In [15]:
df_csv = pd.read_csv("students.csv")

In [16]:
print(df_csv.head())

  student  Math  Science  English
0       A    78       85       82
1       B    90       88       85
2       C    67       76       80
3       D    95       92       90
4       E    88       79       84

In [21]:
df_csv.dtypes

student    object
Math        int64
Science     int64
English     int64
dtype: object

In [22]:
df_csv.isnull()

   student   Math  Science  English
0    False  False    False    False
1    False  False    False    False
2    False  False    False    False
3    False  False    False    False
4    False  False    False    False

In [25]:
df_csv.sum()

student    ABCDE
Math         418
Science      420
English      421
dtype: object

In [24]:
df_csv.isnull().sum()

student    0
Math       0
Science    0
English    0
dtype: int64

In [26]:
df.to_json("students.json", orient="records", indent=4)  
df_json = pd.read_json("students.json") 
print(df_json)

  student  Math  Science  English
0       A    78       85       82
1       B    90       88       85
2       C    67       76       80
3       D    95       92       90
4       E    88       79       84

In [27]:
import sqlite3

In [28]:
conn = sqlite3.connect("school.db")
df.to_sql("students", conn, if_exists="replace", index=False)

5

In [29]:
sql_df = pd.read_sql("SELECT * FROM students", conn) 
print(sql_df)

  student  Math  Science  English
0       A    78       85       82
1       B    90       88       85
2       C    67       76       80
3       D    95       92       90
4       E    88       79       84

In [33]:
sql_df = pd.read_sql("SELECT * FROM students WHERE Math > 80", conn)
print(sql_df)

  student  Math  Science  English
0       B    90       88       85
1       D    95       92       90
2       E    88       79       84

In [34]:
count_df = pd.read_sql("SELECT COUNT(*) AS Total_Students FROM students", conn)
print(count_df)

   Total_Students
0               5

In [42]:
url = "https://www.w3schools.com/html/html_tables.asp"  
tables = pd.read_html(url)  
print("Total Tables Found:", len(tables))  
df_web = tables[0] 
print(df_web.head())

Total Tables Found: 2
                        Company          Contact  Country
0           Alfreds Futterkiste     Maria Anders  Germany
1    Centro comercial Moctezuma  Francisco Chang   Mexico
2                  Ernst Handel    Roland Mendel  Austria
3                Island Trading    Helen Bennett       UK
4  Laughing Bacchus Winecellars  Yoshi Tannamuri   Canada

In [40]:
!pip install lxml

Collecting lxml
  Downloading lxml-6.1.1-cp313-cp313-win_amd64.whl.metadata (3.6 kB)
Downloading lxml-6.1.1-cp313-cp313-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.0 MB 87.9 kB/s eta 0:00:40
   ----- ---------------------------------- 0.5/4.0 MB 87.9 kB/s eta 0:00:40
   ----- ---------------------------------- 0.5/4.0 MB 87.9 kB/s eta 0:00:40
   ----- ---------------------------------- 0.5/4.0 MB 87.9 kB/s eta 0:00:40
   ----- ---------------------------------- 0.5/4.0 MB 87.9 kB/s eta 0:00:40
   ----- ---------------------------------- 0.5/4.0 MB 87.9 kB/s eta 0:00:40
   ----- ---------------------------------- 0.5/4.0 MB 87.9 kB/s eta 0:00:40
   ----- ---------------------------------- 0.5/4.0 MB 87.9 kB/s eta 0:00:40
   ----- ---------------------------------- 0.5/4.0 MB 87.9 kB/s eta 0:00:40
   ----- ---------------------------------- 0.5/4.0 MB 87.9 kB/s eta 0:00:40
   ----- ---------------------------------- 0.5/4.0 MB 87.9 kB/s eta 0:00:40
   ----- ---------------------------------- 0.5/4.0 MB 87.9 kB/s eta 0:00:40
   ----- ---------------------------------- 0.5/4.0 MB 87.9 kB/s eta 0:00:40
   ----- ---------------------------------- 0.5/4.0 MB 87.9 kB/s eta 0:00:40
   ----- ---------------------------------- 0.5/4.0 MB 87.9 kB/s eta 0:00:40
   ----- ---------------------------------- 0.5/4.0 MB 87.9 kB/s eta 0:00:40
   ----- ---------------------------------- 0.5/4.0 MB 87.9 kB/s eta 0:00:40
   ----- ---------------------------------- 0.5/4.0 MB 87.9 kB/s eta 0:00:40
   ----- ---------------------------------- 0.5/4.0 MB 87.9 kB/s eta 0:00:40
   ----- ---------------------------------- 0.5/4.0 MB 87.9 kB/s eta 0:00:40
   ----- ---------------------------------- 0.5/4.0 MB 87.9 kB/s eta 0:00:40
   ----- ---------------------------------- 0.5/4.0 MB 87.9 kB/s eta 0:00:40
   ----- ---------------------------------- 0.5/4.0 MB 87.9 kB/s eta 0:00:40
   ----- ---------------------------------- 0.5/4.0 MB 87.9 kB/s eta 0:00:40
   ------- -------------------------------- 0.8/4.0 MB 63.1 kB/s eta 0:00:51
   ------- -------------------------------- 0.8/4.0 MB 63.1 kB/s eta 0:00:51
   ------- -------------------------------- 0.8/4.0 MB 63.1 kB/s eta 0:00:51
   ------- -------------------------------- 0.8/4.0 MB 63.1 kB/s eta 0:00:51
   ------- -------------------------------- 0.8/4.0 MB 63.1 kB/s eta 0:00:51
   ------- -------------------------------- 0.8/4.0 MB 63.1 kB/s eta 0:00:51
   ---------- ----------------------------- 1.0/4.0 MB 83.1 kB/s eta 0:00:36
   ---------- ----------------------------- 1.0/4.0 MB 83.1 kB/s eta 0:00:36
   ---------- ----------------------------- 1.0/4.0 MB 83.1 kB/s eta 0:00:36
   ---------- ----------------------------- 1.0/4.0 MB 83.1 kB/s eta 0:00:36
   ---------- ----------------------------- 1.0/4.0 MB 83.1 kB/s eta 0:00:36
   ------------- -------------------------- 1.3/4.0 MB 97.9 kB/s eta 0:00:28
   --------------- ------------------------ 1.6/4.0 MB 120.1 kB/s eta 0:00:21
   ------------------ --------------------- 1.8/4.0 MB 141.2 kB/s eta 0:00:16
   -------------------- ------------------- 2.1/4.0 MB 162.3 kB/s eta 0:00:12
   ----------------------- ---------------- 2.4/4.0 MB 183.1 kB/s eta 0:00:09
   -------------------------- ------------- 2.6/4.0 MB 202.5 kB/s eta 0:00:07
   -------------------------- ------------- 2.6/4.0 MB 202.5 kB/s eta 0:00:07
   ---------------------------- ----------- 2.9/4.0 MB 214.4 kB/s eta 0:00:06
   ------------------------------- -------- 3.1/4.0 MB 232.8 kB/s eta 0:00:04
   ---------------------------------- ----- 3.4/4.0 MB 249.8 kB/s eta 0:00:03
   ---------------------------------------- 4.0/4.0 MB 290.4 kB/s eta 0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.1.1

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [43]:
print(df_web.columns)

Index(['Company', 'Contact', 'Country'], dtype='object')

In [44]:
print(df_web.shape[0])

6

In [45]:
germany = df_web[df_web["Country"] == "Germany"]

print(germany)

               Company       Contact  Country
0  Alfreds Futterkiste  Maria Anders  Germany

In [46]:
df_web.to_csv("companies_web.csv", index=False)

In [47]:
print(df.mean(numeric_only=True)) 
print(df.median(numeric_only=True)) 
print(df.mode(numeric_only=True))
print(df.var(numeric_only=True)) 
print(df.std(numeric_only=True))

Math       83.6
Science    84.0
English    84.2
dtype: float64
Math       88.0
Science    85.0
English    84.0
dtype: float64
   Math  Science  English
0    67       76       80
1    78       79       82
2    88       85       84
3    90       88       85
4    95       92       90
Math       124.3
Science     42.5
English     14.2
dtype: float64
Math       11.148991
Science     6.519202
English     3.768289
dtype: float64

In [49]:
Q1 = df.quantile(0.25, numeric_only=True)  
Q2 = df.quantile(0.50, numeric_only=True)  
Q3 = df.quantile(0.75, numeric_only=True) 
IQR = Q3 - Q1 
print(Q1, Q2, Q3, IQR)

Math       78.0
Science    79.0
English    82.0
Name: 0.25, dtype: float64 Math       88.0
Science    85.0
English    84.0
Name: 0.5, dtype: float64 Math       90.0
Science    88.0
English    85.0
Name: 0.75, dtype: float64 Math       12.0
Science     9.0
English     3.0
dtype: float64

In [50]:
subject_range = df.max(numeric_only=True) - df.min(numeric_only=True)

print(subject_range)

Math       28
Science    16
English    10
dtype: int64

In [51]:
mean_marks = df.mean(numeric_only=True)

In [52]:
print(mean_marks.idxmin())

Math

In [53]:
variance = df.var(numeric_only=True)
print(variance.idxmax())

Math

In [54]:
mean_scores = df[["Math","Science","English"]].mean()  
  
above_all = df[  
    (df["Math"] > mean_scores["Math"]) &  
    (df["Science"] > mean_scores["Science"]) &  
    (df["English"] > mean_scores["English"])  
]  
print(above_all)  
print(df.sort_values(by="English", ascending=False))

  student  Math  Science  English
1       B    90       88       85
3       D    95       92       90
  student  Math  Science  English
3       D    95       92       90
1       B    90       88       85
4       E    88       79       84
0       A    78       85       82
2       C    67       76       80

In [55]:
math_above = df[df["Math"] > mean_scores["Math"]]

print(math_above)

  student  Math  Science  English
1       B    90       88       85
3       D    95       92       90
4       E    88       79       84

In [56]:
df["Total"] = df["Math"] + df["Science"] + df["English"]

In [57]:
top2 = df.sort_values(by="Total", ascending=False).head(2)

print(top2)

  student  Math  Science  English  Total
3       D    95       92       90    277
1       B    90       88       85    263

In [59]:
data = {  
    "Student":["A","B","C","D","E"],  
    "Math":[78,None,67,95,88],  
    "Science":[85,88,"absent",92,79],  
    "English":[82,85,80,90,None]  
}  
dirty_df = pd.DataFrame(data) 
print(dirty_df)

  Student  Math Science  English
0       A  78.0      85     82.0
1       B   NaN      88     85.0
2       C  67.0  absent     80.0
3       D  95.0      92     90.0
4       E  88.0      79      NaN

In [64]:
print(dirty_df.isnull().sum())

Student    0
Math       1
Science    0
English    1
dtype: int64

In [65]:
dirty_df["Science"] = dirty_df["Science"].replace("absent", pd.NA)
dirty_df["Science"] = pd.to_numeric(dirty_df["Science"])
science_mean = dirty_df["Science"].mean()
dirty_df["Science"] = dirty_df["Science"].fillna(science_mean)

In [66]:
dirty_df["Math"] = dirty_df["Math"].fillna(dirty_df["Math"].mean())

In [60]:
df["Total"] = df[["Math","Science","English"]].sum(axis=1) 
df.to_csv("processed_students.csv", index=False)

In [67]:
dirty_df["Math"] = pd.to_numeric(dirty_df["Math"])

dirty_df["Science"] = pd.to_numeric(dirty_df["Science"])

dirty_df["English"] = pd.to_numeric(dirty_df["English"])

In [68]:
print(dirty_df)
print(dirty_df.dtypes)

  Student  Math  Science  English
0       A  78.0     85.0     82.0
1       B  82.0     88.0     85.0
2       C  67.0     86.0     80.0
3       D  95.0     92.0     90.0
4       E  88.0     79.0      NaN
Student     object
Math       float64
Science    float64
English    float64
dtype: object

In [69]:
import matplotlib.pyplot as plt  
df.plot(x="Student", y="Total", kind="bar", legend=False) 
plt.title("Total Score of Each Student") 
plt.show()

KeyError: 'Student'